version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_acme_widget_basket
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    command: php -S 0.0.0.0:8000 -t public
